### PR TITLE
updated the mpas plotting scripts

### PR DESCRIPTION
**Pull request by delippi**
Updated the mpas plotting scripts (the domain check also has plotting script built in) to correctly plot mpas domain edges. Prior to this update the concave boundaries would be filled by the plotting routines incorrectly leading to potential misinterpretation of data. The scripts were also cleaned up a little.

This fixes the following issue: https://github.com/NOAA-EMC/RDASApp/issues/173

### CODE REVIEW

**Review by ShunLiu-NOAA — DISMISSED** [review]
Looks good to me. Thank you for the update.

**Comment by SamuelDegelia-NOAA** [comment]
Nice solution @delippi. It looks like these python scripts assume "mpasout" files for the backgrounds. Do you want to hold off on merging this until #161 is merged? Also out of curiousity, what is reason for the difference in the increment vs. spread plots where the latter uses the extra `tri.simplices` argument in the `Triangulation` function?

**Comment by delippi** [comment]
> Nice solution @delippi. It looks like these python scripts assume "mpasout" files for the backgrounds. Do you want to hold off on merging this until #161 is merged? Also out of curiousity, what is reason for the difference in the increment vs. spread plots where the latter uses the extra `tri.simplices` argument in the `Triangulation` function?

Good catch. That was not needed. I will update accordingly. That just allowed you to specify the triangulation. It works fine without that option.

**Comment by guoqing-noaa** [comment]
@delippi Maybe you can change "mpasout" back to "restart" and test it with the latest RDASApp?
PR #161 will need more time to investigate. We would like to get your PR merged first.

**Comment by delippi** [comment]
@SamuelDegelia-NOAA & @guoqing-noaa, I've reverted to the use of restart.nc instead of mpasout.nc and checked that it still works.

**Review by SamuelDegelia-NOAA — APPROVED** [review]

**Review by ShunLiu-NOAA — APPROVED** [review]

**Review by guoqing-noaa — APPROVED** [review]

**Pull request merged**
