### PR TITLE
Update MPAS-JEDI ctests for new 2024052700 case 

### LINKED ISSUE #126: Update ctest for new MPAS-JEDI case
Now that the 2024052700 case is added and well-tested, we can make plans to update the MPAS-JEDI ctest to the new case. I am opening this issue to invite further discussion on the topic. 

The directory structure is different for this new case so some edits will need to be made to `rrfs-test/CMakeLists.txt`. 

Additionally, as we add more obs types unique to RRFS, it would be helpful to keep only two ctests - one for EnVar and one for LETKF/GETKF. That way we do not add more and more ctests for each new obs type. 

Until we start using JCB, we can make use of the directory structures that @delippi created in `rrfs-test/validated_yamls`. As new obs types are added under `rrfs-test/validated_yamls/templates/obtype_config`, we can cat these together along with a header file for the specific solver. And then that newly created yaml could be used as a ctest. 

Any thoughts from others?

### PR DESCRIPTION
**Pull request by SamuelDegelia-NOAA**
The new 20240527 MPAS case has been sufficiently tested by various developers in RDASApp. This PR thus updates the MPAS-JEDI ctest to use this new case. 

Since these test data are pretty large with 30 ensemble members, I integrated @guoqing-noaa's link script into `build.sh`. Then, the `expr/mpas_2024052700` directory is copied into `bundle/rrfs-test-data/rrfs-data_mpasjedi_2024052700` to be consistent with how we generated the ctests before. Since this case directory is mostly links, it is very fast to copy it into `bundle` and later into `build/rrfs-test` for each ctest. 

This PR also adds a ctest for BUMP to better track if code changes impact our results (such as the geometry changes in #121).

Note: these ctests use the sounding IODA observations included with the new case. I have another PR in development that will use the observations in `RDASApp/rrfs-test/validated_yamls` to generate new yaml files for the ctest using all the obs yamls we have validated (see my fork [here](https://github.com/SamuelDegelia-NOAA/RDASApp/tree/feature/update_ctest)). But there are still some references to the previous case (and GSI geovals) in those obs space yamls, so we need to edit them first before I introduce those additional changes. 

Here are the results of the ctests using the new case:   

```
[Samuel.Degelia@hfe12 rrfs-test]$ ctest
Test project /scratch1/NCEPDEV/da/Samuel.Degelia/RDASApp_dev/RDASApp/build/rrfs-test
    Start 1: rrfs_fv3jedi_hyb_2022052619
1/6 Test #1: rrfs_fv3jedi_hyb_2022052619 .........***Failed    4.14 sec
    Start 2: rrfs_fv3jedi_letkf_2022052619
2/6 Test #2: rrfs_fv3jedi_letkf_2022052619 .......***Failed    3.93 sec
    Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
3/6 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar ...   Passed   69.37 sec
    Start 4: rrfs_mpasjedi_2024052700_letkf
4/6 Test #4: rrfs_mpasjedi_2024052700_letkf ......   Passed   59.74 sec
    Start 5: rrfs_mpasjedi_2024052700_getkf
5/6 Test #5: rrfs_mpasjedi_2024052700_getkf ......   Passed   41.58 sec
    Start 6: rrfs_mpasjedi_2024052700_bumploc
6/6 Test #6: rrfs_mpasjedi_2024052700_bumploc ....   Passed  133.65 sec

67% tests passed, 2 tests failed out of 6

Label Time Summary:
mpi            = 312.42 sec*proc (6 tests)
rdas-bundle    = 312.42 sec*proc (6 tests)
script         = 312.42 sec*proc (6 tests)

Total Test time (real) = 312.51 sec

```

The failed ctests are only for fv3-jedi executables (#133). 

If this PR is merged, I will also update the wiki pages that reference the mpas-jedi ctests.

### CODE REVIEW

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA I will have a look into the fv3jedi failure cases as soon as possible. 
A question, did you "module load RDAS/hera*lua"  when you ran the ctest?

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA This is great. Thanks for moving this forward!

I think we are now at a point about the future direction: do we want to spend the effort to fix fv3-related issues in RDASApp? @ShunLiu-NOAA @hu5970 

It will be good if we have time and resources to keep fv3 updated in RDASApp. But I think we do have limited resources and FTEs, so it will be our highest priority to push forward on the MPASJEDI front. One option is to leave fv3 as is in RDASApp and any limited future works on fv3 may use the fv3-bundle and Skylab which are well maintained and supported by JCSDA.

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Yes I loaded the RDAS modules before running the ctest. The executables crash with the same error even when running them outside of ctests using job scripts that load the modules. Thanks for looking into this! 

@guoqing-noaa, The big thing we still use fv3-jedi for in RDASApp is validating observation hofx against GSI. @delippi is doing a lot of work in this area. So we should still get to the bottom of this problem with the fv3jedi executables crashing. 

But for the ctests, I don't think that there is really any need to keep the fv3-jedi ctests. I don't know anyone using them.

**Comment by guoqing-noaa** [comment]
Yes, thank @delippi for setting up and doing lots of hofx validation work. I understand that's a critical part. I am totally fine if we have the resources to fix fv3-related issues.

When @hu5970 worked on syncing all the sub-modules,  he spent significant effort in making the fv3 part work. I am not sure whether we want to do that repeatedly in the future.

@SamuelDegelia-NOAA I agree with you that for this PR, we can remove ctests #1 and #2.

**Comment by SamuelDegelia-NOAA** [comment]
I saw on @hu5970's original PR that the fv3jedi ctests were passing so I am not sure what might have changed. It could be user error on my end if someone else wouldn't mind checking to see if they get the same errors (even just running the ctests). And agreed @guoqing-noaa, will update the PR to remove those fv3jedi ctests.

**Comment by TingLei-NOAA** [comment]
To make fv3-jedi in rdasapp still work should not require any significant resources (in terms of FTE).   In addition to what @SamuelDegelia-NOAA mentioned fv3-jedi is used,  the generic characteristics of jedi  make fv3-jedi a helpful secondary testbed (also a reference) for developments on mpas jedi codes like mgbf has always first taken fv3 as the first test for its' regular grids compared with irregular grids in mpas.   
Especially when global jedi deveopers are actively working on fv3jedi, it would be very helpful for us to , at least, maintain fv3-edi work in rdasapp to follow new enhancement in jedi (maybe, in terms of fv3-jedi in some way).

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Could you modify init.sh to change /lfs4 to /lfs5 as in PR #137? I will close that one.

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA  I cloned the current rdasapp (after setting up for the right fms , see PR https://github.com/NOAA-EMC/RDASApp/pull/138) and both fv3jedi rrfs tests (hyb and letkf)  passed as shown in /scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-emc-rdas/RDASApp/build/ctest_rrfs_fv3jedi.out .

**Comment by guoqing-noaa** [comment]
2 tests failed on Jet:

```
[Jet|fe3 rrfs-test]$ ctest               
Test project /lfs5/BMC/wrfruc/gge/RDASApp/build/rrfs-test                          
    Start 1: rrfs_mpasjedi_2024052700_Ens3Dvar                                     
1/4 Test #1: rrfs_mpasjedi_2024052700_Ens3Dvar ...***Failed   96.48 sec            
    Start 2: rrfs_mpasjedi_2024052700_letkf                                        
2/4 Test #2: rrfs_mpasjedi_2024052700_letkf ......   Passed  136.49 sec            
    Start 3: rrfs_mpasjedi_2024052700_getkf                                        
3/4 Test #3: rrfs_mpasjedi_2024052700_getkf ......   Passed   72.26 sec            
    Start 4: rrfs_mpasjedi_2024052700_bumploc                                      
4/4 Test #4: rrfs_mpasjedi_2024052700_bumploc ....***Failed   15.25 sec            

50% tests passed, 2 tests failed out of 4

Label Time Summary:                      
mpi            = 320.47 sec*proc (4 tests)                                         
rdas-bundle    = 320.47 sec*proc (4 tests)                                         
script         = 320.47 sec*proc (4 tests)                                         

Total Test time (real) = 320.82 sec      

The following tests FAILED:              
          1 - rrfs_mpasjedi_2024052700_Ens3Dvar (Failed)                           
          4 - rrfs_mpasjedi_2024052700_bumploc (Failed)                            
Errors while running CTest               
Output from these tests are in: /lfs5/BMC/wrfruc/gge/RDASApp/build/rrfs-test/Testing/Temporary/LastTest.log                                                            
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely. 
```

**Comment by guoqing-noaa** [comment]
I just confirmed that I can run the mpasjedi and bumploc cases using `link_mpasjedi_expr.sh`，
Need further investigation on why those two cases failed in CTests.

**Comment by ShunLiu-NOAA** [comment]
> @SamuelDegelia-NOAA I cloned the current rdasapp (after setting up for the right fms , see PR #138) and both fv3jedi rrfs tests (hyb and letkf) passed as shown in /scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-emc-rdas/RDASApp/build/ctest_rrfs_fv3jedi.out .

Should we merge Ting's PR first?

**Comment by guoqing-noaa** [comment]
> Should we merge Ting's PR first?

@ShunLiu-NOAA Let's test Ting's PR first. Thanks!

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA 
I made a clean build on Jet and now all 4 tests passed!   Also, all tests passed on Hera. 
```
100% tests passed, 0 tests failed out of 4

Label Time Summary:
mpi            = 417.00 sec*proc (4 tests)
rdas-bundle    = 417.00 sec*proc (4 tests)
script         = 417.00 sec*proc (4 tests)

Total Test time (real) = 417.09 sec

```

**Review by guoqing-noaa — CHANGES_REQUESTED** [review]
LGTM. 

PR #142 resolved the libfv3.so issue, so you can bring back the fv3jedi tests. Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
Thanks @guoqing-noaa, @TingLei-NOAA, @ShunLiu-NOAA for working to track down the FV3 bug over the weekend! I synced my fork with #142 and now all of the FV3 ctests are working again. I have added those back in for this PR, so please re-review! 

```
Test project /scratch1/NCEPDEV/da/Samuel.Degelia/RDASApp_dev/RDASApp/build/rrfs-test
    Start 1: rrfs_fv3jedi_hyb_2022052619
1/6 Test #1: rrfs_fv3jedi_hyb_2022052619 .........   Passed  102.89 sec
    Start 2: rrfs_fv3jedi_letkf_2022052619
2/6 Test #2: rrfs_fv3jedi_letkf_2022052619 .......   Passed   17.42 sec
    Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
3/6 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar ...   Passed  109.65 sec
    Start 4: rrfs_mpasjedi_2024052700_letkf
4/6 Test #4: rrfs_mpasjedi_2024052700_letkf ......   Passed   40.54 sec
    Start 5: rrfs_mpasjedi_2024052700_getkf
5/6 Test #5: rrfs_mpasjedi_2024052700_getkf ......   Passed   42.12 sec
    Start 6: rrfs_mpasjedi_2024052700_bumploc
6/6 Test #6: rrfs_mpasjedi_2024052700_bumploc ....   Passed  125.84 sec

100% tests passed, 0 tests failed out of 6

Label Time Summary:
mpi            = 438.46 sec*proc (6 tests)
rdas-bundle    = 438.46 sec*proc (6 tests)
script         = 438.46 sec*proc (6 tests)

Total Test time (real) = 438.49 sec
```

**Review by guoqing-noaa — APPROVED** [review]

**Review by ShunLiu-NOAA — APPROVED** [review]

**Pull request merged**
