### PR TITLE
Python converter for EFCLAM BUFR DUMP Data

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
This PR adds a Python converter for EFCLAM BUFR DUMP data.

The converter will be used to transform EFCLAM BUFR data into IODA (netCDF) format. Following steps similar to GDASApp, a Python file and a JSON description file were created.

The following two files are new:

~/IODA/python/bufr2ioda_efclam.py
~/IODA/python/bufr2ioda_efclam.json

Related issue: https://github.com/NOAA-EMC/RDASApp/issues/205

Validation for the output observation and IODA variable naming has been performed.

### CODE REVIEW

**Comment by SamuelDegelia-NOAA** [comment]
Hi @PraveenKumar-NOAA, do you happen to have a sample `efclam` bufr file that we can use with this PR? I believe I have the `lghtng` data to test #212.

**Comment by PraveenKumar-NOAA** [comment]
> Hi @PraveenKumar-NOAA, do you happen to have a sample `efclam` bufr file that we can use with this PR? I believe I have the `lghtng` data to test #212.

@SamuelDegelia-NOAA there is no efclam data file in the RRFS test data, hence I used an RTMA file to validate the converter. I can send you this file or you are welcome to pick any efclam bufr file to test the converter.

**Comment by SamuelDegelia-NOAA** [comment]
Could you send me the RTMA file? I do not have any other bufr files with efclam data at the moment. Thanks!

**Comment by PraveenKumar-NOAA** [comment]
> Could you send me the RTMA file? I do not have any other bufr files with efclam data at the moment. Thanks!

@SamuelDegelia-NOAA please use this file from Hercules - /work2/noaa/da/pkumar/dump/rtma.t00z.efclam.tm00.bufr_d

**Review by SamuelDegelia-NOAA — APPROVED** [review]
Thanks @PraveenKumar-NOAA, this converter works well for me too! 

As an aside for any other reviewers, we need to make 1-2 small changes to the code here to test the converters inside RDASApp. This is because of how we name the staged bufr/prepbufr files for our MPAS test case. But these converters are meant to be general and file names might change in the workflow. So this behavior is expected for the current status of RDASApp.

**Review by delippi — APPROVED** [review]
It took a little bit to figure out what needed changed for the generic setup to work with our staged data, but wasn't too difficult. One thing I noticed was that the DUMP variable doesn't seem to be used in the `run_bufr2ioda.sh` that is in the wiki instructions, but instead uses cycle_type in the .json file. I think this is a good base to easily make updates for specific use in the workflow.

**Pull request merged**
