### PR TITLE
Sync RDASApp submodules with upstream repositories 

### PR DESCRIPTION
**Pull request by SamuelDegelia-NOAA**
This PR syncs the RDASApp submodules with their respective upstream repositories. Each submodule is updated to the head of their develop branches. Here are the updated hashes for each submodule: 

```
fv3-jedi:        d3c800b -> 2c72009
fv3-jedi-lm:     a6e97d7 -> 3254bb8
ioda:            d49ed17 -> eaacb84
iodaconv:        b540ace -> 1bce7ab
mpas-jedi:       b9d596d -> 0edc6b9
oops:            d772173 -> b2e6d27
saber:           bba6f7e -> ac8d8aa
ufo:             94d50d6 -> 7c9d9a3
vader:           6d56a1e -> aedb250
```

The `ufo-data` and `ioda-data` staged data are also updated under the role accounts and their links are updated in RDASApp. The `mpas-jedi-data` and `fv3-jedi-data` directories are already up to date. Here are the new hashes (the directories are now also labeled in `RDAS_DATA`):

```
ufo-data: b45d99e
ioda-data: 25afc2c
```
Note that CRTM, MPAS, and gsibec submodules are not updated since we have those set as tagged versions.  

Following some variable name updates in UFO, some of the yaml files were also updated. Also, fv3-jedi now expects pressure variables named `DELP` instead of `delp`, so the fv3-jedi case data for rrfs-test has also been updated. Thanks to @delippi for making those variable changes. 

Finally, the EnVar test in rrfs-test failed with a small reference mismatch error, so the test reference data there has also been updated.

The `ufo`, `mpas-jedi`, `fv3-jedi`, and `rrfs-test` ctests were run as part of this update. I will update the PR with results from these tests momentarily. 

EDIT: Updated instructions for syncing submodules with upstream repositories can be found [here](https://github.com/NOAA-EMC/RDASApp/wiki/Sync-RDASApp-submodule-with-upstream-repositories).

### CODE REVIEW

**Comment by SamuelDegelia-NOAA** [comment]
Results from UFO ctests

```
99% tests passed, 4 tests failed out of 511

Label Time Summary:
GEOS                  = 239.06 sec*proc (3 tests)
HofX                  = 710.66 sec*proc (10 tests)
QC                    = 1205.69 sec*proc (16 tests)
UV                    = 159.29 sec*proc (2 tests)
actions               =  15.83 sec*proc (4 tests)
aircraft              = 216.35 sec*proc (3 tests)
compo                 = 152.88 sec*proc (2 tests)
crtm                  = 620.77 sec*proc (54 tests)
errors                = 1309.44 sec*proc (8 tests)
executable            = 3193.51 sec*proc (52 tests)
filters               = 10660.14 sec*proc (193 tests)
fov                   =  27.01 sec*proc (3 tests)
gnssro                =  74.25 sec*proc (1 test)
instrument            = 2069.23 sec*proc (28 tests)
metoffice             =  77.36 sec*proc (2 tests)
mpi                   = 15888.14 sec*proc (475 tests)
obsfunctions          = 568.40 sec*proc (87 tests)
operators             = 872.21 sec*proc (150 tests)
ozone                 =   0.77 sec*proc (2 tests)
pibal                 =  75.89 sec*proc (1 test)
predictors            = 132.33 sec*proc (27 tests)
profile               = 194.51 sec*proc (41 tests)
radarVAD              = 161.01 sec*proc (2 tests)
rass                  = 159.91 sec*proc (2 tests)
satwinds              = 268.74 sec*proc (3 tests)
scatwinds             = 234.16 sec*proc (3 tests)
script                = 12756.23 sec*proc (459 tests)
sfcLand               = 238.35 sec*proc (3 tests)
sfcMarine             = 239.63 sec*proc (3 tests)
sonde                 = 247.28 sec*proc (3 tests)
ufo                   = 15949.74 sec*proc (511 tests)
unit_tests            = 457.32 sec*proc (95 tests)
utils                 =   8.87 sec*proc (2 tests)
variablenamemap       =   2.84 sec*proc (1 test)
variabletransforms    = 103.47 sec*proc (24 tests)

Total Test time (real) = 15968.22 sec

The following tests FAILED:
        146 - ufo_test_tier1_test_ufo_qc_variableassignment (Failed)
        166 - ufo_test_tier1_test_ufo_tropics_qc_filters (Failed)
        494 - ufo_test_tier1_test_ufo_variabletransforms_rhumidity (Failed)
        497 - ufo_test_tier1_test_ufo_variabletransforms_shumidity (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/BMC/zrtrr/Samuel.Degelia/RDASApp_updatesub/RDASApp/build/ufo/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.  
```

For these four failures, test 146 already failed before this update due to a floating point reference error. Test 166 fails due to a CRTM error (likely due to our CRTM version lagging behind that used for the `ufo` repo). 

Tests 494 and 497 fail due to a UFO update from a few days ago that expects an error but that did not occur in my testing. So because that error did not occur, it considers the ctest failed. Overall I do not think this is a concern.

**Comment by SamuelDegelia-NOAA** [comment]
Results from fv3-jedi ctests 

```
94% tests passed, 7 tests failed out of 127

Label Time Summary:
fv3-jedi    = 971.16 sec*proc (126 tests)
fv3jedi     = 975.27 sec*proc (127 tests)
mpi         = 962.61 sec*proc (115 tests)
script      = 975.27 sec*proc (127 tests)

Total Test time (real) = 976.05 sec

The following tests FAILED:
         70 - fv3jedi_test_tier1_hofx_nomodel_abi_radii (Failed)
         88 - fv3jedi_test_tier1_hyb-3dvar (Failed)
         91 - fv3jedi_test_tier1_3dvar_lam_cmaq (Failed)
         96 - fv3jedi_test_tier1_hyb-fgat_fv3lm (Failed)
         98 - fv3jedi_test_tier1_4denvar (Failed)
         99 - fv3jedi_test_tier1_4denvar_seq (Failed)
        111 - fv3jedi_test_tier1_diffstates_lam_cmaq (Failed)
Errors while running CTest
Output from these tests are in: /scratch1/BMC/zrtrr/Samuel.Degelia/RDASApp_ufobugfix/RDASApp/build/fv3-jedi/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

We expect these tests to fail as documented in the [Wiki page here](https://github.com/NOAA-EMC/RDASApp/wiki/Sync-RDASApp-submodule-with-upstream-repositories) and thus these are not a concern.

**Comment by SamuelDegelia-NOAA** [comment]
Results from mpas-jedi ctests

```
The following tests FAILED:
         37 - test_mpasjedi_3denvar_amsua_allsky (Failed)
         38 - test_mpasjedi_3denvar_amsua_bc (Failed)
         40 - test_mpasjedi_3dfgat (Failed)
         43 - test_mpasjedi_4denvar_VarBC (Failed)
         44 - test_mpasjedi_4denvar_VarBC_nonpar (Failed)
         47 - test_mpasjedi_4dfgat (Failed)
         54 - test_mpasjedi_lgetkf_height_vloc (Failed)
```

Again, we expect these tests to fail as documented in the [Wiki page here](https://github.com/NOAA-EMC/RDASApp/wiki/Sync-RDASApp-submodule-with-upstream-repositories) and thus these are not a concern.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for the PR. We really need this.

@Junjun-NOAA Does this PR meet your need on the new SABER codes?

**Comment by SamuelDegelia-NOAA** [comment]
Results from `rrfs-test` ctests: 

```
(eva) [Samuel.Degelia@hfe07 rrfs-test]$ ctest -j7
Test project /scratch1/BMC/zrtrr/Samuel.Degelia/RDASApp_updatesub/RDASApp/build/rrfs-test
    Start 4: rrfs_mpasjedi_2024052700_getkf_observer
    Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
    Start 6: rrfs_mpasjedi_2024052700_bumploc
    Start 1: rrfs_fv3jedi_hyb_2022052619
    Start 2: rrfs_fv3jedi_letkf_2022052619
    Start 7: rrfs_bufr2ioda_msonet
1/7 Test #7: rrfs_bufr2ioda_msonet .....................   Passed   28.78 sec
2/7 Test #2: rrfs_fv3jedi_letkf_2022052619 .............   Passed   52.06 sec
3/7 Test #1: rrfs_fv3jedi_hyb_2022052619 ...............   Passed  124.14 sec
4/7 Test #6: rrfs_mpasjedi_2024052700_bumploc ..........   Passed  178.97 sec
5/7 Test #4: rrfs_mpasjedi_2024052700_getkf_observer ...   Passed  551.88 sec
    Start 5: rrfs_mpasjedi_2024052700_getkf_solver
6/7 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar .........   Passed  578.95 sec
7/7 Test #5: rrfs_mpasjedi_2024052700_getkf_solver .....   Passed  1370.04 sec

100% tests passed, 0 tests failed out of 7

Label Time Summary:
mpi            = 2884.83 sec*proc (7 tests)
rdas-bundle    = 2884.83 sec*proc (7 tests)
script         = 2884.83 sec*proc (7 tests)

Total Test time (real) = 1922.68 sec
```

**Comment by Junjun-NOAA** [comment]
> @SamuelDegelia-NOAA Thanks for the PR. We really need this.
> 
> @Junjun-NOAA Does this PR meet your need on the new SABER codes?

@guoqing-noaa Yes, this PR has exactly the same SABER codes as I am using.  Thanks @SamuelDegelia-NOAA for this PR.

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by delippi** [comment]
@SamuelDegelia-NOAA, thanks for putting this together. Make sure to update the instructions on the wiki and it would be nice if you could link it to your initial comment on this PR as well.

I have a hunch as to why some of the ufo ctests fail. I have a couple of PRs I'm working on in `ufo` and `fv3-jedi` that might fix that as well as some other issues. But as you say, that isn't an issue for now.

**Review by delippi — APPROVED** [review]

**Comment by SamuelDegelia-NOAA** [comment]
> @SamuelDegelia-NOAA, thanks for putting this together. Make sure to update the instructions on the wiki and it would be nice if you could link it to your initial comment on this PR as well.
> 
> I have a hunch as to why some of the ufo ctests fail. I have a couple of PRs I'm working on in `ufo` and `fv3-jedi` that might fix that as well as some other issues. But as you say, that isn't an issue for now.

Definitely will do - working up updating those instructions now.

**Comment by SamuelDegelia-NOAA** [comment]
Note: I have not synced `RDAS_DATA` between Hera and Orion/Jet yet. I was planning to do that this morning but forgot about the maintenance. So we should wait until I can sync those data tomorrow before running any CI tests.

**Review by hu5970 — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
@hu5970 and @delippi Thanks for reviewing this PR. I think we can merge this PR now.

**Comment by delippi** [comment]
> @hu5970 and @delippi Thanks for reviewing this PR. I think we can merge this PR now.

I think so. @SamuelDegelia-NOAA do we need to wait for any tests on other machines or any staging of data on any machine?

**Comment by SamuelDegelia-NOAA** [comment]
All the data is staged now, but I would like to run the rrfs tests on Orion/Hercules before merging. I have not done any testing there yet. It looks like the CI tests aren't running there, so I'll manually build and do some tests.

**Comment by guoqing-noaa** [comment]
FYI, the test on Hercules did not start because there is a leftover from a previous CI test which stopped in the mid-stage due to the HPC maintenance.

**Comment by SamuelDegelia-NOAA** [comment]
> FYI, the test on Hercules did not start because there is a leftover from a previous CI test which stopped in the mid-stage due to the HPC maintenance. 

Ah I see, thanks for the explanation and for restarting the tests @guoqing-noaa!

**Comment by SamuelDegelia-NOAA** [comment]
I think this PR is good to merge now that the Hercules/Orion test passed. Thanks all for reviewing.

**Review by guoqing-noaa — APPROVED** [review]

**Pull request merged**
