### PR TITLE
Add validated mesonet yamls. And made minor changes to validation tools.

### PR DESCRIPTION
**Pull request by delippi**
This PR will merge: 
* mesonet (obtype 188) yamls that have been validated for hofx and oberror for airTemperature, specificHumidity, windEastward, windNortward, and stationPressure.
*  Some minor updates to the non-eva validation tools.

Issues:
This PR covers Issue #80
In addition there is a supplemental Issue #54 which adds justification for accepting some slight differences in final hofx and oberror.

### CODE REVIEW

**Review by CoryMartin-NOAA — COMMENTED** [review]
Until we have proper YAML generation set up with JCB here, can we at least split apart the obs sections from the redundant background, background error, etc. sections. Like use `cat` + one YAML and then the `validated_yamls` to create the 'real YAML' that way we don't have the same few hundred lines duplicated in several places?

**Comment by delippi** [comment]
> Until we have proper YAML generation set up with JCB here, can we at least split apart the obs sections from the redundant background, background error, etc. sections. Like use `cat` + one YAML and then the `validated_yamls` to create the 'real YAML' that way we don't have the same few hundred lines duplicated in several places?

Thanks @CoryMartin-NOAA. I had considered that, but I wasn't sure which would be best. I think it is a great suggestion. I will work on that.

**Comment by ShunLiu-NOAA** [comment]
@CoryMartin-NOAA, Good suggestion. We are currently preparing a new MPAS test case. Once the new test case is ready, we will organize the related functionality testing, for example, reducing redundant session in YAML files and unifying YAML format to align with VAR and EnKF test case.

**Comment by delippi** [comment]
@CoryMartin-NOAA, I was able to come up with a quick solution. One of my favorite tools to use is the stream editor (sed). I put a placeholder variable `@OBSERVATIONS@` in the yaml under basic_config and then that gets replaced with the contents of which ever obtype config yaml is chosen when you run gen_yaml.sh.

**Comment by CoryMartin-NOAA** [comment]
>  One of my favorite tools to use is the stream editor (sed). 

@delippi you're an old soul :-)

**Comment by SamuelDegelia-NOAA** [comment]
This is great! The only comment I have is in regard to the split yamls. If we cat these individual yamls together then the 

```
  observations:
     observers:
```

lines will repeat in the merged file. I'm not sure if that will throw an error or not. Should we remove the first two lines of the individual yamls to instead start with `- obs space:`?

**Comment by delippi** [comment]
@SamuelDegelia-NOAA, good suggestion. I was only thinking of combining one of the obtype yamls with the basic configuration yaml at the moment. I think this is all a temporary storage solution anyway since we will move to JCB in a few months or so. I kind of don't have a preference on this. I will go ahead and make the change unless anyone objects.

**Comment by SamuelDegelia-NOAA** [comment]
I just ask because it looks like GDASApp does something similar (e.g., https://github.com/NOAA-EMC/jcb-gdas/blob/develop/observations/atmosphere/sfc.yaml.j2). But I agree that this is just a temporary storage solution so either way works.

**Comment by delippi** [comment]
@CoryMartin-NOAA do you guys have any tools for enforcing certain formatting standards for yamls? That would be great to start doing here.

**Comment by CoryMartin-NOAA** [comment]
@delippi it's hard because we are using Jinja2 templates so they're non-standard YAML. We mainly just test to make sure they are valid YAML at the end

**Review by SamuelDegelia-NOAA — APPROVED** [review]

**Review by TingLei-NOAA — APPROVED** [review]

**Review by ShunLiu-NOAA — APPROVED** [review]

**Pull request merged**
