### PR TITLE
Update modulefiles for Orion after Rocky 9 switch

### LINKED ISSUE #78: Update Orion modules for switch from CentOS 7 to Rocky 9
Orion is currently being upgraded from CentOS 7 to Rocky 9. Per discussion [here](https://github.com/NOAA-EMC/GSI/issues/754), the spack-stack framework will need to be rebuilt for Orion after the upgrade. This will then require us to update the paths and compiler versions in `modulefiles/EVA/orion.lua` and `modulefiles/RDAS/orion.intel.lua`. 

The spack-stack upgrades for Orion can be tracked in [spack-stack issue #981](https://github.com/JCSDA/spack-stack/issues/981). Until these modules are rebuilt, building and running RDASApp on Orion will likely not work.

### PR DESCRIPTION
**Pull request by SamuelDegelia-NOAA**
This PR modifies `RDASApp/modulefiles/orion.intel.lua` for required changes after the Orion OS was switched from CentOS 7 to Rocky 9. This follows the updates in [GDASApp PR #1180](https://github.com/NOAA-EMC/GDASApp/pull/1180) (thanks @RussTreadon-NOAA). After updating the modules, all exes build successfully and the rrfs-test ctests pass: 

```
(base) orion-login-2[33] sdegelia$ module use RDASApp/modulefiles
(base) orion-login-2[34] sdegelia$ module load RDAS/orion.intel
(gdasapp) orion-login-2[35] sdegelia$ cd RDASApp/build/rrfs-test/
(gdasapp) orion-login-2[37] sdegelia$ ctest
Test project /work/noaa/wrfruc/sdegelia/RDASApp_rocky/RDASApp/build/rrfs-test
    Start 1: rrfs_fv3jedi_hyb_2022052619
1/5 Test #1: rrfs_fv3jedi_hyb_2022052619 ............   Passed  201.92 sec
    Start 2: rrfs_fv3jedi_letkf_2022052619
2/5 Test #2: rrfs_fv3jedi_letkf_2022052619 ..........   Passed   63.20 sec
    Start 3: rrfs_mpasjedi_2022052619_Ens3Dvar
3/5 Test #3: rrfs_mpasjedi_2022052619_Ens3Dvar ......   Passed   75.52 sec
    Start 4: rrfs_mpasjedi_2022052619_atms_npp_qc
4/5 Test #4: rrfs_mpasjedi_2022052619_atms_npp_qc ...   Passed  130.87 sec
    Start 5: rrfs_mpasjedi_2022052619_letkf
5/5 Test #5: rrfs_mpasjedi_2022052619_letkf .........   Passed   81.59 sec

100% tests passed, 0 tests failed out of 5

Label Time Summary:
mpi            = 553.09 sec*proc (5 tests)
rdas-bundle    = 553.09 sec*proc (5 tests)
script         = 553.09 sec*proc (5 tests)

Total Test time (real) = 553.16 sec
```

A couple of notes: 

1. Loading the modulefiles gives the warning: `The following dependent module(s) are not currently loaded: py-numpy/1.22.3 (required by: bufr/12.0.1), python/3.10.13 (required by: boost/1.83.0, bufr/12.0.1, fckit/0.11.0, atlas/0.35.1, py-pybind11/2.11.0)`. Everything still builds successfully but perhaps something to keep an eye on in the future. 
2. I also tested running the eva tools and the associated modules in `RDASApp/modulefiles/EVA/orion.lua` and everything works without any changes there.

### CODE REVIEW

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
@SamuelDegelia-NOAA Thank you for this update.

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA  Thanks for taking care of this.  After this upgrading, are rdasapp and gdasapp using different modules  or still the same  , the former's could be regarded as a duplicate of the latter?

**Comment by SamuelDegelia-NOAA** [comment]
@TingLei-NOAA Yes rdasapp and gdasapp are using the same modules again after this PR. These updates follow a PR made to the corresponding orion modulefile for gdasapp.

**Review by guoqing-noaa — APPROVED** [review]

**Comment by TingLei-NOAA** [comment]
@SamuelDegelia-NOAA  Thanks for the clarification.  I 'd also recommend to explicitly give a link pointing to the gdasapp pr which you mentioned. 
That is great you tested this new setup.

**Review by TingLei-NOAA — APPROVED** [review]

**Comment by SamuelDegelia-NOAA** [comment]
> @SamuelDegelia-NOAA Thanks for the clarification. I 'd also recommend to explicitly give a link pointing to the gdasapp pr which you mentioned. That is great you tested this new setup.

Good call - I just updated the main post to include the GDASApp PR.

**Pull request merged**
