### PR TITLE
hotfix on init.sh and libfv3.so

### PR DESCRIPTION
**Pull request by guoqing-noaa**
bug fix on init.sh for jet (lfs4 -> lfs5)
bug fix on sorc/fv3-interface.cmake resolving the runtime error-cannot loading libfv3.so

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
Successfully build and run ctests on Hera:
`/scratch1/BMC/wrfruc/gge/tmp/RDASApp/build/rrfs-test`
and Jet:
`/lfs5/BMC/wrfruc/gge/RDASApp/build/rrfs-test`

**Comment by guoqing-noaa** [comment]
This PR will close issue #133 
and this PR needs to be merged before Sam's PR #134

**Comment by TingLei-NOAA** [comment]
@guoqing, it seems your fork is not using the same commits for those submodules (including fv3).  For fork repo, seems only "Synchronize Fork" won't update the submodules.   
My PR (about use of fms submodule) is just to make the current rdasapp buiding successful (while can't reproduce the fv3 lib issue,while removing that fv3-interface.cmak).  If your PR is the solution for both successful building and the fms for the current RDASapp with its' current submodule commits , that will be great!

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA 
> @guoqing, it seems your fork is not using the same commits for those submodules (including fv3). For fork repo, seems only "Synchronize Fork" won't update the submodules. 

Could you be more specific about the above comment?

Also, to clarify, Sam and I both can build the current RDASApp without a problem. I suspect your build failure may not be related to the current RDADApp. Could you try a fresh clone and build?

If you review, approve and we merge PR #141,  then we can build and test a fresh clone as follows:
```
git clone https://github.com/rrfsx/rdas_build_test.git
cd rdas_build_test
./build_test.sh NOAA-EMC develop fv3-lam # assume fv3-lam is your Hera slurm account
```
Or test this PR as follows:
`./build_test.sh guoqing-noaa hotfix fv3-lam`   

Of course, you can always manually clone, build, and test a fresh clone. Thanks!

**Comment by TingLei-NOAA** [comment]
@Guoqing Ge - NOAA Affiliate ***@***.***>  What I did was, started
from a fork of yours and then "git pull" and then , "git checkout your PR
branch.
The commits  for submodules in your PR is gq-list_submodule.txt in
hera://home/Ting.Lei/dr-out,
the commits for the current rdasapp is in rdasapplist_submodule.txt.
Your could double check on those commits on your side.
Hope this helps.
Ting

______________________________

Ting Lei

Physical Scientist, Contractor with Lynker in support of

EMC/NCEP/NWS/NOAA

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA I only modified init.sh and sorc/fv3-interface.cmake based on the latest develop branch:
https://github.com/NOAA-EMC/RDASApp/pull/142/files
So there should NOT be any changes in other parts (including submodules).

**Could you start from a fresh clone?** I did that.

Also, on Hera, this is my testing directory:
`/scratch1/BMC/wrfruc/gge/tmp/RDASApp`
Enter my directory, run `git log`, you will see that I only modifed two files as shown in the above.
I also checked out the `develop` branch there, so you can also run `git diff develop hotfix` to see changes.

**Comment by TingLei-NOAA** [comment]
@gquoqing, An easy way is you just check to see the commit for fv3 in your
pr and that in rdasapp and let me know if they are the same.
Thanks.
Ting

______________________________

Ting Lei

Physical Scientist, Contractor with Lynker in support of

EMC/NCEP/NWS/NOAA

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.***

301-683-3624

**Comment by guoqing-noaa** [comment]
> @gquoqing, An easy way is you just check to see the commit for fv3 in your pr and that in rdasapp and let me know if they are the same. Thanks. Ting

@TingLei-NOAA They are the same on my side.

If you think they are different, could you do this at your side?
'git clone --recursive -b hotfix git@github.com:guoqing-noaa/RDASApp.git  RDASAPP-ge'

Once it is checked out at your side, send the location to me and I can take a look.

**Comment by TingLei-NOAA** [comment]
@guoqing-noaa  Thanks for this clarification. I would re-do some steps on both repo to get the same commits.

**Review by TingLei-NOAA — APPROVED** [review]
This PR does work for the current RDASapp. 
Approved.

**Comment by guoqing-noaa** [comment]
@TingLei-NOAA Thanks for testing and confirming this PR works as expected.

If I don't hear anything further, I will merge this PR early tomorrow.

**Review by ShunLiu-NOAA — APPROVED** [review]

**Pull request merged**
