### PR TITLE
Feature/issue pr templates

### PR DESCRIPTION
**Pull request by delippi**
## Description
This PR adds Issue and PR templates under the `RDASApp/.github` directory. This will make our PR and Issues better by: 

- **Consistency:** PR templates establish a standard for all contributions, making it easier to review and understand pull requests. 
- **Clarity:** Templates prompt contributors to include all necessary information, which clarifies the purpose and context of the PR. 

Suggestions on the formatting and add/removing sections are most welcome! I just based these on the templates from other JCSDA repos.

**To test**: An easy way to view the formatting is going to a browser based Markdown previewer then copy and paste the contents from any of these files:
```
RDASApp/.github/ISSUE_TEMPLATE/bug-report.md
RDASApp/.github/ISSUE_TEMPLATE/general-issue.md
RDASApp/.github/pull_request_template.md
RDASApp/.github/PULL_REQUEST_TEMPLATE/sync_submodule_pr.md
RDASApp/.github/PULL_REQUEST_TEMPLATE/bugfix_pr.md
RDASApp/.github/PULL_REQUEST_TEMPLATE/feature_pr.md
```

There will be two options for creating a new issue: 

- bug-report 
- general-issue

There will be three options for PRs:

- bugfix_pr
- feature_pr
- sync_submodule_pr

**NOTE:** The templating for pull requests is a little challenging. Github doesn't seem to automatically create drop down button to select the template. Instead, the default template will have the links to expand the URL for the desired template. All it does is add "&template=bugfix_pr.md" to the existing PR and will auto fill in markdown text from that template.

## Issue(s) addressed
- I didn't create an issue.

## Dependencies (if applicable)
List the other PRs that this PR is dependent on:
- None

## Checklist
- [x] I have tested the feature locally.

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
@delippi Could you also update this to the default branch of your fork? This way, we can try creating PRs on your fork to see what the PR templates look like in practice? Thanks!

**Comment by delippi** [comment]
Sure @guoqing-noaa. I just made `feature/issue_pr_templates` my default branch in my fork. I just need to remember to change it back and hopefully we can get this PR through quickly! I believe this should work. This was also how I was testing things myself.

And for quick reference:
https://github.com/delippi/RDASApp

**Comment by SamuelDegelia-NOAA** [comment]
Great idea, thanks for adding this @delippi. My only question is related to `feature_pr.md`. Do we want to mention that the rrfs-test ctests only need to be run if updating source code or yamls used by the ctests? For example, if adding new utilities I do not think we need to run rrfs-test.

**Comment by guoqing-noaa** [comment]
@delippi Thanks for setting up a testing sandbox!

A few comments:
1. Once one selects among "feature/bugfix/submodule", it is finalized and we cannot go back to change the category unless one start over from the beginning.  This may not be convenient as one may do a wrong click.
I think it may be okay to use only one template for all.

2. about the checklist:
```
## Checklist
- [ ] Unit tests added/updated (if applicable).
- [ ] I have done a self review of my code.
- [ ] I have tested the feature locally.
- [ ] I have run the rrfs-test unit test.
```
(1) I don't think we have unit tests in the top-level RDASApp which integrates JEDI subcomponents
(2) "I have run the rrfs-test unit test" --->  "I have run the rrfs tests."

3. about "Issue(s)":
```
## Issue(s) addressed
> What issues does this fix?
Results are documented in Issue
- Add your issue number here.
```
Have we decided that each PR has to open at least one corresponding issue? @ShunLiu-NOAA @hu5970 

4. about "sample result"
```
## Sample Result (optional)
> Add a screenshot with the final result.
```
I would recommend we don't include sample screenshots in the first post of the description which always make that post super long and verbose.  We can encourage sample results in the follow-up posts.

**Comment by delippi** [comment]
> Great idea, thanks for adding this @delippi. My only question is related to `feature_pr.md`. Do we want to mention that the rrfs-test ctests only need to be run if updating source code or yamls used by the ctests? For example, if adding new utilities I do not think we need to run rrfs-test.

Fair point. I think I can add something in that regard.

**Comment by guoqing-noaa** [comment]
For the submodule update, we already have a good wiki. I think we can direct anyone to refer to that wiki  and hence don't need a separate PR template for that.

**Comment by delippi** [comment]
@guoqing-noaa, I've responded in line to each of your comments below.
 
> @delippi Thanks for setting up a testing sandbox!
> 
> A few comments:
> 
> 1. Once one selects among "feature/bugfix/submodule", it is finalized and we cannot go back to change the category unless one start over from the beginning.  This may not be convenient as one may do a wrong click.
>    I think it may be okay to use only one template for all.

Thanks for stress testing this! I didn't notice the struggle that might occur. I found a way to easily go back. You can just remove `?expand=1&template=feature_pr.md` from the URL and reselect. Or you can just change which template is used by directly modifying the URL. It is easier to just go back and reselect. I can add a note to every template on how to do this. I think it would be really useful to have more than just the default template. I would really like to have a separate template for the submodule updates to make sure everything was documented and structured consistently each time. Yes, a user could look at the previous submodule update PRs but there is no guarantee. This would help ensure there is some standard that is being followed, plus it is easier if the formatting is already done. As for what that standard is I am definitely open to suggestions. If there is overwhelming support for just having a single PR template we can go that route as well.

> 2. about the checklist:
> 
> ```
> ## Checklist
> - [ ] Unit tests added/updated (if applicable).
> - [ ] I have done a self review of my code.
> - [ ] I have tested the feature locally.
> - [ ] I have run the rrfs-test unit test.
> ```
> 
> (1) I don't think we have unit tests in the top-level RDASApp which integrates JEDI subcomponents (2) "I have run the rrfs-test unit test" ---> "I have run the rrfs tests."
> 

This is an easy fix, thanks.

> 3. about "Issue(s)":
> 
> ```
> ## Issue(s) addressed
> > What issues does this fix?
> Results are documented in Issue
> - Add your issue number here.
> ```
> 
> Have we decided that each PR has to open at least one corresponding issue? @ShunLiu-NOAA @hu5970

That is the encouraged practice, but I don't think it is always necessary or will always be enforced. For example, I didn't add one for this PR. It seems like just extra clutter in the repo especially for simple additions and there wouldn't be any other useful information different from what is in the description of this PR. For larger PRs, I think we should enforce. This is just my opinion. The section here is to help encourage the best practice regardless of how big or small the PR.

> 
> 4. about "sample result"
> 
> ```
> ## Sample Result (optional)
> > Add a screenshot with the final result.
> ```
> 
> I would recommend we don't include sample screenshots in the first post of the description which always make that post super long and verbose. We can encourage sample results in the follow-up posts.

I'm fine with removing this. I included a sample result at the top of my PR#188. I thought it adds some helpful context especially when the Issue can have a lot of comments and sometimes hard to find a final result.

> For the submodule update, we already have a good wiki. I think we can direct anyone to refer to that wiki and hence don't need a separate PR template for that.

That is true. I was hoping to have a specific template for the submodule updates. I really liked how @SamuelDegelia-NOAA's PR was detailed and I added some organization and structure that we can follow. I'm hopeful that I can still convince you that we should have more than one PR template.

**Comment by ShunLiu-NOAA** [comment]
@delippi, Good idea to create PR templates.

**Review by SamuelDegelia-NOAA — APPROVED** [review]

**Comment by ShunLiu-NOAA** [comment]
@guoqing-noaa I think it is better to open at least one corresponding issue for a PR.

**Comment by delippi** [comment]
Are there any remaining comments on this PR? If not, I think we can get this one merged in so we can start using the templates.

**Review by ShunLiu-NOAA — APPROVED** [review]

**Pull request merged**
