### PR TITLE
Add a simple offline domain check for IODA observations to work with halo obs. distribution

### PR DESCRIPTION
**Pull request by SamuelDegelia-NOAA**
This PR adds a simple tool under `RDASApp/rrfs-test/IODA/offline_domaincheck.py` to allow for the assimilation of the RAP observations created from `bufr2ioda.x` with halo observation distribution. The tool takes in a list of IODA files, creates a new file with the `_dc` prefix standing for "domain check", and then fills the new file in with any observations inside the specified region. This allows the regional LETKF to work with the `bufr2ioda.x` observations. 

As discussed previous, this is just a temporary workaround for #51 until the bug in IODA or UFO can be resolved, or until the `ReduceObsSpace` filter action is fully working for our test case.  

I did not include any scripts for running this, but all you need to do is edit the top of `offline_domaincheck.py` to give a list of the input IODA files and then the latitude/longitude ranges for the simple domain check. The example `lat_range` and `lon_range` in the script work for the fv3-jedi test case in RDASApp and allow LETKF to successfully run with the IODA observations.  These ranges would need to change whenever we get the MPAS test domain configured, but hopefully the underlying issue will be resolved by then.

### CODE REVIEW

**Review by TingLei-NOAA — APPROVED** [review]

**Review by guoqing-noaa — APPROVED** [review]
Nice tool! Looks good to me.

Did you check the obs distribution before and after this domain check?

**Comment by SamuelDegelia-NOAA** [comment]
> Nice tool! Looks good to me.
> 
> Did you check the obs distribution before and after this domain check?

Good question - I should have shown that in the PR. Here are the observations (1) before and (2) after running `offline_domaincheck.py`. 

1. Before 
dist_obs

2. After
dist_obs_dc

The tool is working as intended by removing obs far away from the domain. The obs just outside the domain (e.g., southwest Canada or Mexico) are not a problem since they are included in halo regions as long as the halo radius isn't very small.

**Review by ShunLiu-NOAA — APPROVED** [review]

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for the figures! Nice!

It looks like the halo radius is not small in Fig. 2. Do you know what the radius is? Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
The halo radius is set to 1250km which is sufficient to capture those obs just outside the domain

**Pull request merged**
