### PR TITLE
Add bufr2ioda ctest

### PR DESCRIPTION
**Pull request by SamuelDegelia-NOAA**
This is a draft PR to add a bufr2ioda ctest following #171. This shows how we can use the `iodaconv_comp.sh` tool to compare against a reference IODA file.

Here, a new ctest is added called `rrfs_bufr2ioda_msonet`. It runs `bufr2ioda.x` for a given prepbufr file. Then, `iodaconv_comp_rrfs.sh` is run to compare the output between the `ioda_msonet.nc` generated during the ctest and a reference  version. 

Output from ctest: 

```
1/1 Test #7: rrfs_bufr2ioda_msonet ............   Passed  585.70 sec

The following tests passed:
        rrfs_bufr2ioda_msonet

100% tests passed, 0 tests failed out of 1

Label Time Summary:
mpi            = 585.70 sec*proc (1 test)
rdas-bundle    = 585.70 sec*proc (1 test)
script         = 585.70 sec*proc (1 test)

Total Test time (real) = 585.71 sec
```

Output from ctest but changing the pressure scaling from 100 to 90 in the input yaml file: 

```
7: DIFFER : VARIABLE : pressure : POSITION : [521497] : VALUES : 101930 <> 91737 : PERCENT : 10
...
...
7: DIFFER : VARIABLE : pressure : POSITION : [521504] : VALUES : 101930 <> 91737 : PERCENT : 10
1/1 Test #7: rrfs_bufr2ioda_msonet ............***Failed   38.01 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
mpi            =  38.01 sec*proc (1 test)
rdas-bundle    =  38.01 sec*proc (1 test)
script         =  38.01 sec*proc (1 test)

Total Test time (real) =  38.10 sec

The following tests FAILED:
          7 - rrfs_bufr2ioda_msonet (Failed)
```

There is still some work to clean up the additions to `rrfs-test/CMakeLists.txt`, and I would like to add a test for the python bufr2ioda converter. But this shows that this type of test is possible and can be added to RDASApp pretty easily.

### CODE REVIEW

**Comment by SamuelDegelia-NOAA** [comment]
I think this PR is ready for review now. Since PR #192 is still under review, we can plan to add a ctest later for the python-based converter. 

```
(eva) [Samuel.Degelia@hfe10 rrfs-test]$ (eva) [Samuel.Degelia@hfe10 rrfs-test]$ ctest -j7
Test project /scratch1/BMC/zrtrr/Samuel.Degelia/RDASApp_dev/RDASApp/build/rrfs-test
    Start 3: rrfs_mpasjedi_2024052700_Ens3Dvar
    Start 4: rrfs_mpasjedi_2024052700_getkf_observer
    Start 6: rrfs_mpasjedi_2024052700_bumploc
    Start 1: rrfs_fv3jedi_hyb_2022052619
    Start 2: rrfs_fv3jedi_letkf_2022052619
    Start 7: rrfs_bufr2ioda_msonet
1/7 Test #7: rrfs_bufr2ioda_msonet .....................   Passed   42.52 sec
2/7 Test #2: rrfs_fv3jedi_letkf_2022052619 .............   Passed   57.09 sec
3/7 Test #1: rrfs_fv3jedi_hyb_2022052619 ...............   Passed  118.83 sec
4/7 Test #4: rrfs_mpasjedi_2024052700_getkf_observer ...   Passed  1943.64 sec
    Start 5: rrfs_mpasjedi_2024052700_getkf_solver
5/7 Test #6: rrfs_mpasjedi_2024052700_bumploc ..........   Passed  2083.63 sec
6/7 Test #3: rrfs_mpasjedi_2024052700_Ens3Dvar .........   Passed  4477.88 sec
7/7 Test #5: rrfs_mpasjedi_2024052700_getkf_solver .....   Passed  3735.32 sec

100% tests passed, 0 tests failed out of 7

Label Time Summary:
mpi            = 12458.90 sec*proc (7 tests)
rdas-bundle    = 12458.90 sec*proc (7 tests)
script         = 12458.90 sec*proc (7 tests)

Total Test time (real) = 5679.05 sec
```

**Review by TingLei-NOAA — DISMISSED** [review]

**Comment by delippi** [comment]
@SamuelDegelia-NOAA, thanks for putting this together. Should we wait until I finalize the mesonet bufr2ioda yaml in my other PR #183 and Praveen's PR #181? I was also waiting to finalize those with my other PR #188 to make sure I didn't miss anything. It might not matter since we can always just update accordingly and we will just have everything already in place.

**Comment by SamuelDegelia-NOAA** [comment]
@delippi That is probably a good idea. Works for me!

**Review by hu5970 — DISMISSED** [review]

**Comment by SamuelDegelia-NOAA** [comment]
The failed ctest on Jet was due to the job running out of memory. I switched from using `--exclusive` to `--mem=64G`. The ctest is working for me now, but feel free to rerun the CI @guoqing-noaa

**Comment by guoqing-noaa** [comment]
> The failed ctest on Jet was due to the job running out of memory. I switched from using `--exclusive` to `--mem=64G`. The ctest is working for me now, but feel free to rerun the CI @guoqing-noaa

@SamuelDegelia-NOAA Thanks for fixing this!

**Comment by guoqing-noaa** [comment]
FYI, some of Hercules nodes are in maintenance and that's why we have not gotten the CI test results from Hercules yet.
image

**Comment by guoqing-noaa** [comment]
Let's merge this first to facilitate PR #209

**Review by guoqing-noaa — APPROVED** [review]
LGTM.

**Pull request merged**
